CREATE TABLE News (
	NewsID INT(4) NOT NULL AUTO_INCREMENT,
	NewsTitle VARCHAR(255) NOT NULL,
	NewsContent TEXT NOT NULL,
	NewsTag VARCHAR(20) NOT NULL,
	TIMEDATE datetime NOT NULL, 
	NewsShot VARCHAR(50),
	CONSTRAINT NewsID_pk PRIMARY KEY (NewsID) 
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT =1 ;

INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow1.png');
INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow2.png');
INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow3.png');
INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow4.png');
INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow5.png');
INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow6.png');
INSERT INTO news VALUES ('', 'NEWS_TITLE_TEST_T_LEARNING', 'THIS IS TEST NEWS CONTENT FOR T-LEARNING WEB TEST APPLICATION', 'NEWS', NOW() , 'imgshow7.png');

SELECT NewsID, NewsTitle, NewsContent, NewsTag, TIMEDATE, NewsShot, DATE(TIMEDATE) AS DATE, TIME(TIMEDATE) AS TIME FROM NEWS 